---

- name: Provision with Docker
  hosts: 
    - core
    - source
    - web
  roles:
    - angstwad.docker_ubuntu
  become: yes

- name: Up Agora
  hosts: core
  roles:
    - common
    - agora
  vars:
    update: true
    compose: "{{ composes.agora }}"
  become: yes

- name: Up Harvesters
  hosts: source
  roles:     
    - common
    - harvesters
  vars:     
    update: true
    compose: "{{ composes.harvesters }}"   
  become: yes

- name: Up metric services
  hosts: core
  roles:     
    - common
    - metrics
  vars:
    compose: "{{ composes.metrics }}"
    update: true
  become: yes

- name: Up web & api
  hosts: web
  roles:
    - common
    - web
  vars:
    compose: "{{ composes.web }}"
    update: true
  become: yes
